name: Release
on: workflow_dispatch
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check package
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --dry-run
